name: Deploying Assignment week 3

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  workflow_dispatch: 

env:
  APP_ENV: ${{ secrets.APP_ENV }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Print env variable
        run: echo "$APP_ENV"

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Providing permission to app and tesh
        run : chmod +x test.sh app.sh 

      - name: Run app.sh
        run: ./app.sh

      - name: Run test.sh
        run: ./test.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-result
          path: .